change task rebalancing threshold as well
igo95862/cfs-zen-tweaks pull request #8
Opened 2022-02-09 20:40 UTC by dim-geo

Zen also changes default task rebalancing threshold
https://github.com/zen-kernel/zen-kernel/commit/05429691ac69cfe6704530bfed1d5911efb828bb

2022-02-09 20:53 UTC, igo95862 requested changes

2022-02-09 20:53 UTC, igo95862 commented on set-cfs-zen-tweaks.sh
>      echo "Detected kernel <5.13. Using legacy locations."
What about legacy `/proc` location?

2022-02-09 20:53 UTC, igo95862 commented on set-cfs-zen-tweaks.sh
>      echo "Detected kernel <5.13. Using legacy locations."
It might be `/proc/sys/kernel/sched_nr_migrate`.

2022-02-09 22:07 UTC, dim-geo commented on set-cfs-zen-tweaks.sh
>      echo "Detected kernel <5.13. Using legacy locations."
I don't have a lower kernel available to confirm

2022-02-10 19:05 UTC, igo95862 commented on set-cfs-zen-tweaks.sh
>      echo "Detected kernel <5.13. Using legacy locations."
I will try a VM with older kernel this weekend and merge.

2022-02-12 09:39 UTC, merged

2023-08-05 10:52 UTC, simonvanderveldt commented
@dim-geo The linked zen-kernel commit also removed the migration cost override. Shouldn't that also be removed from `cfs-zen-tweaks.sh`?